name: Forward forked PR coverage

on:
  workflow_run:
    # match the name of the other workflow here:
    workflows: ["CI"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.16'

      - name: Coverage Comment
        uses: mutility/coverpkg@v1
        with:
          comment: replace
